const FETCH_ALL_RECIPES = "FETCH_ALL_RECIPES";
const CREATE_RECIPE = "CREATE_RECIPE";
const UPDATE_RECIPE = "UPDATE_RECIPE";
const DELETE_RECIPE = "DELETE_RECIPE";
const AUTHENTICATION ="AUTHENTICATION";
const LOGOUT ="LOGOUT";

export {
    FETCH_ALL_RECIPES,
    CREATE_RECIPE,
    UPDATE_RECIPE,
    DELETE_RECIPE,
    AUTHENTICATION,
    LOGOUT

}